import { Language } from '../../types';

export type Screen =
  | 'lang'
  | 'welcome'
  | 'login'
  | 'forgot'
  | 'role'
  | 'register'
  | 'passenger'
  | 'driver'
  | 'results'
  | 'trip'
  | 'booking'
  | 'request'
  | 'review';

export const today = '2026-05-25';

export const localizedCopy = {
  [Language.RU]: {
    languageName: 'Русский',
    welcomeTitle: 'Добро пожаловать в Hamroh',
    welcome: 'Надёжные поездки между городами Таджикистана',
    login: 'Войти',
    register: 'Зарегистрироваться',
    forgotPassword: 'Забыли пароль?',
    recoverPassword: 'Восстановить пароль',
    resetPasswordTitle: 'Восстановление пароля',
    resetPasswordHint: 'Введите номер телефона, код подтверждения и новый пароль. В демо код: 7171.',
    verificationCode: 'Код подтверждения',
    newPassword: 'Новый пароль',
    savePassword: 'Сохранить пароль',
    password: 'Пароль',
    repeatPassword: 'Повтор',
    firstName: '???',
    lastName: 'Фамилия',
    roleChoice: 'Кем вы хотите пользоваться Hamroh?',
    passengerRole: 'Я пассажир',
    passengerRoleDescription: 'Быстрая регистрация без проверки администратора',
    driverRole: 'Я водитель',
    driverRoleDescription: 'Понадобятся документы и проверка модератором',
    passengerRegister: 'Регистрация пассажира',
    driverRegister: 'Регистрация водителя',
    male: 'Мужчина',
    female: 'Женщина',
    search: 'Поиск',
    trips: 'Поездки',
    messages: 'Сообщения',
    notifications: 'Уведомления',
    profile: 'Профиль',
    driverHome: 'Главная',
    create: 'Создать',
    requests: 'Заявки',
    welcomeBack: 'Добро пожаловать',
    from: 'Откуда',
    to: 'Куда',
    date: 'Дата',
    passengers: 'Пассажиры',
    verified: 'Проверен',
    baggage: 'Багаж',
    woman: 'Женщина',
    findRide: 'Найти поездку',
    addressRide: 'Мне нужна поездка от адреса',
    active: 'Активные',
    completed: 'Завершенные',
    noActiveTrips: 'Актуальных поездок пока нет',
    noCompletedTrips: 'Завершенных поездок пока нет',
    newCount: 'новых',
    noNotifications: 'Уведомлений пока нет',
    tapToOpen: 'Нажмите, чтобы открыть',
    deleteNotification: 'Удалить уведомление',
    accept: 'Принять',
    reject: 'Отклонить',
    market: 'Рынок поездок',
    noTripsFromCity: 'Пока нет поездок из этого города',
    exactTime: 'Точное время',
    whenFull: 'По наполнении',
    price: 'Цена',
    seats: 'Мест',
    onePrice: 'Одна цена',
    byRows: 'По рядам',
    pickupAddress: 'Точный адрес посадки',
    dropoffPoint: 'Точка высадки',
    driverComment: 'Комментарий водителя',
    publishRide: 'Опубликовать поездку',
    foundTrips: 'Найдено поездок',
    noTripsFound: 'Поездок не найдено. Измените дату, маршрут или количество мест.',
    fastest: 'Быстрее всех',
    seatsShort: 'мест',
    driver: 'Водитель',
    tripsWord: 'поездки',
    save: 'Сохранить',
    cancel: 'Отмена',
    close: 'Закрыть'
  },
  [Language.TJ]: {
    languageName: 'Тоҷикӣ',
    chooseLanguage: 'Забони барномаро интихоб кунед',
    welcomeTitle: 'Хуш омадед ба Hamroh',
    welcome: 'Сафарҳои боэътимод байни шаҳрҳои Тоҷикистон',
    login: 'Ворид шудан',
    register: 'Рӯйхатгирӣ',
    forgotPassword: 'Паролро фаромӯш кардед?',
    recoverPassword: 'Барқарор кардани парол',
    resetPasswordTitle: 'Барқарорсозии парол',
    resetPasswordHint: 'Рақами телефон, рамзи тасдиқ ва пароли навро ворид кунед. Дар демо рамз: 7171.',
    verificationCode: 'Рамзи тасдиқ',
    newPassword: 'Пароли нав',
    savePassword: 'Нигоҳ доштани парол',
    password: 'Парол',
    repeatPassword: 'Такрор',
    firstName: '???',
    lastName: 'Насаб',
    roleChoice: 'Hamroh-ро чӣ гуна истифода мебаред?',
    passengerRole: 'Ман мусофир',
    passengerRoleDescription: 'Рӯйхатгирии зуд бе санҷиши маъмур',
    driverRole: 'Ман ронанда',
    driverRoleDescription: 'Ҳуҷҷатҳо ва санҷиши модератор лозим мешаванд',
    passengerRegister: 'Рӯйхатгирии мусофир',
    driverRegister: 'Рӯйхатгирии ронанда',
    male: 'Мард',
    female: '???',
    search: 'Ҷустуҷӯ',
    trips: 'Сафарҳо',
    messages: 'Паёмҳо',
    notifications: 'Огоҳиҳо',
    profile: 'Профил',
    driverHome: 'Асосӣ',
    create: 'Сохтан',
    requests: 'Дархостҳо',
    welcomeBack: 'Хуш омадед',
    from: 'Аз куҷо',
    to: 'Ба куҷо',
    date: 'Сана',
    passengers: 'Мусофирон',
    verified: 'Санҷида',
    baggage: '???',
    woman: '???',
    findRide: 'Ҷустуҷӯи сафар',
    addressRide: 'Ба ман сафар аз суроға лозим аст',
    active: 'Фаъол',
    completed: 'Анҷомшуда',
    noActiveTrips: 'Ҳоло сафари фаъол нест',
    noCompletedTrips: 'Ҳоло сафари анҷомшуда нест',
    newCount: '???',
    noNotifications: 'Ҳоло огоҳӣ нест',
    tapToOpen: 'Барои кушодан зер кунед',
    deleteNotification: 'Огоҳиро нест кардан',
    accept: 'Қабул',
    reject: '???',
    market: 'Бозори сафарҳо',
    noTripsFromCity: 'Ҳоло аз ин шаҳр сафар нест',
    exactTime: 'Вақти дақиқ',
    whenFull: 'Ҳангоми пур шудан',
    price: 'Нарх',
    seats: '???',
    onePrice: 'Як нарх',
    byRows: 'Аз рӯи қатор',
    pickupAddress: 'Суроғаи дақиқи нишаст',
    dropoffPoint: 'Ҷои фаромадан',
    driverComment: 'Шарҳи ронанда',
    publishRide: 'Нашри сафар',
    foundTrips: 'Сафарҳои ёфтшуда',
    noTripsFound: 'Сафар ёфт нашуд. Сана, масир ё шумораи ҷойҳоро тағйир диҳед.',
    fastest: 'Зудтарин',
    seatsShort: '???',
    driver: 'Ронанда',
    tripsWord: 'сафар',
    save: 'Нигоҳ доштан',
    cancel: 'Бекор',
    close: 'Пӯшидан'
  },
  [Language.EN]: {
    languageName: 'English',
    chooseLanguage: 'Choose app language',
    welcomeTitle: 'Welcome to Hamroh',
    welcome: 'Reliable rides between cities in Tajikistan',
    login: 'Log in',
    register: 'Register',
    forgotPassword: 'Forgot password?',
    recoverPassword: 'Recover password',
    resetPasswordTitle: 'Password recovery',
    resetPasswordHint: 'Enter your phone number, verification code, and a new password. Demo code: 7171.',
    verificationCode: 'Verification code',
    newPassword: 'New password',
    savePassword: 'Save password',
    password: 'Password',
    repeatPassword: 'Repeat',
    firstName: 'First name',
    lastName: 'Last name',
    roleChoice: 'How do you want to use Hamroh?',
    passengerRole: 'I am a passenger',
    passengerRoleDescription: 'Fast registration without admin approval',
    driverRole: 'I am a driver',
    driverRoleDescription: 'Documents and moderator verification are required',
    passengerRegister: 'Passenger registration',
    driverRegister: 'Driver registration',
    male: 'Male',
    female: 'Female',
    search: 'Search',
    trips: 'My rides',
    messages: 'Messages',
    notifications: 'Alerts',
    profile: 'Profile',
    driverHome: 'Home',
    create: 'Create',
    requests: 'Requests',
    welcomeBack: 'Welcome',
    from: 'From',
    to: 'To',
    date: 'Date',
    passengers: 'Passengers',
    verified: 'Verified',
    baggage: 'Baggage',
    woman: 'Woman',
    findRide: 'Find a ride',
    addressRide: 'I need a ride from an address',
    active: 'Active',
    completed: 'Completed',
    noActiveTrips: 'No active rides yet',
    noCompletedTrips: 'No completed rides yet',
    newCount: 'new',
    noNotifications: 'No notifications yet',
    tapToOpen: 'Tap to open',
    deleteNotification: 'Delete notification',
    accept: 'Accept',
    reject: 'Reject',
    market: 'Ride market',
    noTripsFromCity: 'No rides from this city yet',
    exactTime: 'Exact time',
    whenFull: 'When full',
    price: 'Price',
    seats: 'Seats',
    onePrice: 'One price',
    byRows: 'By rows',
    pickupAddress: 'Exact pickup address',
    dropoffPoint: 'Dropoff point',
    driverComment: 'Driver comment',
    publishRide: 'Publish ride',
    foundTrips: 'Rides found',
    noTripsFound: 'No rides found. Change date, route, or seats.',
    fastest: 'Fastest',
    seatsShort: 'seats',
    driver: 'Driver',
    tripsWord: 'rides',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close'
  }
};
