/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  Booking,
  BookingStatus,
  City,
  Complaint,
  ComplaintStatus,
  ComplaintType,
  DriverProfile,
  Language,
  Notification,
  Review,
  Route,
  Trip,
  TripStatus,
  User,
  UserRole,
  Vehicle,
  VerificationStatus,
} from './types';

export const CITIES: City[] = [
  { id: '1', nameRu: 'Душанбе', nameTj: 'Душанбе', nameEn: 'Dushanbe', isActive: true },
  { id: '2', nameRu: 'Худжанд', nameTj: 'Хуҷанд', nameEn: 'Khujand', isActive: true },
  { id: '3', nameRu: 'Бохтар', nameTj: 'Бохтар', nameEn: 'Bokhtar', isActive: true },
  { id: '4', nameRu: 'Куляб', nameTj: 'Кӯлоб', nameEn: 'Kulob', isActive: true },
  { id: '5', nameRu: 'Панджакент', nameTj: 'Панҷакент', nameEn: 'Panjakent', isActive: true },
  { id: '6', nameRu: 'Турсунзода', nameTj: 'Турсунзода', nameEn: 'Tursunzoda', isActive: true },
  { id: '7', nameRu: 'Истаравшан', nameTj: 'Истаравшан', nameEn: 'Istaravshan', isActive: true },
  { id: '8', nameRu: 'Исфара', nameTj: 'Исфара', nameEn: 'Isfara', isActive: true },
  { id: '9', nameRu: 'Канибадам', nameTj: 'Конибодом', nameEn: 'Kanibadam', isActive: true },
];

export const ROUTES: Route[] = [
  { id: 'r1', fromCityId: '1', toCityId: '2', recommendedMinPrice: 150, recommendedMaxPrice: 250, isActive: true },
  { id: 'r2', fromCityId: '1', toCityId: '3', recommendedMinPrice: 40, recommendedMaxPrice: 60, isActive: true },
  { id: 'r3', fromCityId: '1', toCityId: '4', recommendedMinPrice: 70, recommendedMaxPrice: 100, isActive: true },
  { id: 'r4', fromCityId: '1', toCityId: '5', recommendedMinPrice: 120, recommendedMaxPrice: 180, isActive: true },
  { id: 'r5', fromCityId: '1', toCityId: '6', recommendedMinPrice: 20, recommendedMaxPrice: 35, isActive: true },
  { id: 'r6', fromCityId: '2', toCityId: '7', recommendedMinPrice: 20, recommendedMaxPrice: 30, isActive: true },
  { id: 'r7', fromCityId: '2', toCityId: '8', recommendedMinPrice: 40, recommendedMaxPrice: 60, isActive: true },
  { id: 'r8', fromCityId: '2', toCityId: '9', recommendedMinPrice: 30, recommendedMaxPrice: 45, isActive: true },
];

export const SEED_USERS: User[] = [
  {
    id: 'demo_passenger',
    fullName: 'Демо Пассажир',
    phone: '+992501000001',
    password: '7171',
    gender: 'male',
    role: UserRole.Passenger,
    language: Language.RU,
    city: 'Душанбе',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    isActive: true,
    createdAt: '2026-05-28T08:00:00Z',
    updatedAt: '2026-05-28T08:00:00Z',
  },
  {
    id: 'demo_driver',
    fullName: 'Демо Водитель',
    phone: '+992501000002',
    password: '7171',
    gender: 'male',
    role: UserRole.Driver,
    language: Language.RU,
    city: 'Душанбе',
    avatarUrl: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=150',
    isActive: true,
    createdAt: '2026-05-28T08:00:00Z',
    updatedAt: '2026-05-28T08:00:00Z',
  },
  {
    id: 'u1',
    fullName: 'Сомон Файзуллаев',
    phone: '+992900111111',
    password: '7171',
    gender: 'male',
    role: UserRole.Driver,
    language: Language.RU,
    city: 'Душанбе',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
    isActive: true,
    createdAt: '2026-01-10T12:00:00Z',
    updatedAt: '2026-01-10T12:00:00Z',
  },
  {
    id: 'u2',
    fullName: 'Алишер Саидов',
    phone: '+992933222222',
    password: '7171',
    gender: 'male',
    role: UserRole.Driver,
    language: Language.TJ,
    city: 'Худжанд',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    isActive: true,
    createdAt: '2026-02-15T09:30:00Z',
    updatedAt: '2026-02-15T09:30:00Z',
  },
  {
    id: 'u3',
    fullName: 'Дилшод Назаров',
    phone: '+992918333333',
    password: '7171',
    gender: 'male',
    role: UserRole.Passenger,
    language: Language.RU,
    city: 'Душанбе',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    isActive: true,
    createdAt: '2026-03-01T14:20:00Z',
    updatedAt: '2026-03-01T14:20:00Z',
  },
  {
    id: 'u4',
    fullName: 'Мадина Каримова',
    phone: '+992901444444',
    password: '7171',
    gender: 'female',
    role: UserRole.Passenger,
    language: Language.TJ,
    city: 'Худжанд',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    isActive: true,
    createdAt: '2026-03-10T10:00:00Z',
    updatedAt: '2026-03-10T10:00:00Z',
  },
  {
    id: 'u5',
    fullName: 'Фаррух Давлатов',
    phone: '+992985123456',
    password: '7171',
    gender: 'male',
    role: UserRole.Driver,
    language: Language.RU,
    city: 'Бохтар',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150',
    isActive: true,
    createdAt: '2026-04-08T10:00:00Z',
    updatedAt: '2026-04-08T10:00:00Z',
  },
  {
    id: 'admin1',
    fullName: 'Администратор Hamroh',
    phone: '+992000000000',
    password: '7171',
    gender: 'male',
    role: UserRole.Admin,
    language: Language.RU,
    city: 'Душанбе',
    avatarUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150',
    isActive: true,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
  },
];

export const SEED_DRIVER_PROFILES: DriverProfile[] = [
  {
    id: 'dp_demo',
    userId: 'demo_driver',
    verificationStatus: VerificationStatus.Verified,
    licenseNumber: 'DL-DEMO-001',
    licensePhotoUrl: 'demo-license.jpg',
    idDocumentUrl: 'demo-id.jpg',
    rating: 4.9,
    totalTrips: 84,
    cancellationRate: 0.02,
  },
  {
    id: 'dp1',
    userId: 'u1',
    verificationStatus: VerificationStatus.Verified,
    licenseNumber: 'DL-001-2026',
    licensePhotoUrl: 'license-u1.jpg',
    idDocumentUrl: 'id-u1.jpg',
    rating: 4.8,
    totalTrips: 124,
    cancellationRate: 0.03,
  },
  {
    id: 'dp2',
    userId: 'u2',
    verificationStatus: VerificationStatus.Verified,
    licenseNumber: 'DL-002-2026',
    licensePhotoUrl: 'license-u2.jpg',
    idDocumentUrl: 'id-u2.jpg',
    rating: 4.7,
    totalTrips: 91,
    cancellationRate: 0.04,
  },
  {
    id: 'dp5',
    userId: 'u5',
    verificationStatus: VerificationStatus.PendingVerification,
    licenseNumber: 'DL-PENDING-005',
    licensePhotoUrl: 'license-u5.jpg',
    idDocumentUrl: 'id-u5.jpg',
    rating: 0,
    totalTrips: 0,
    cancellationRate: 0,
  },
];

export const SEED_VEHICLES: Vehicle[] = [
  {
    id: 'veh_demo',
    driverId: 'demo_driver',
    brand: 'Toyota',
    model: 'Camry 2022',
    color: 'Белый',
    plateNumber: '0001 TJ 01',
    seats: 4,
    photoUrl: 'demo-car.jpg',
    verificationStatus: VerificationStatus.Verified,
  },
  {
    id: 'veh1',
    driverId: 'u1',
    brand: 'Hyundai',
    model: 'Sonata',
    color: 'Серебристый',
    plateNumber: '7777 TJ 01',
    seats: 4,
    photoUrl: 'car-u1.jpg',
    verificationStatus: VerificationStatus.Verified,
  },
  {
    id: 'veh2',
    driverId: 'u2',
    brand: 'Opel',
    model: 'Astra',
    color: 'Черный',
    plateNumber: '2222 TJ 02',
    seats: 4,
    photoUrl: 'car-u2.jpg',
    verificationStatus: VerificationStatus.Verified,
  },
  {
    id: 'veh5',
    driverId: 'u5',
    brand: 'Toyota',
    model: 'Corolla',
    color: 'Белый',
    plateNumber: '5555 TJ 03',
    seats: 4,
    photoUrl: 'car-u5.jpg',
    verificationStatus: VerificationStatus.PendingVerification,
  },
];

export const SEED_TRIPS = (): Trip[] => [
  {
    id: 'trip1',
    driverId: 'u1',
    vehicleId: 'veh1',
    fromCity: 'Душанбе',
    toCity: 'Худжанд',
    departureDate: '2026-06-03',
    departureTime: '09:00',
    pickupPoint: 'Рудаки 12',
    dropoffPoint: 'Центр Худжанда',
    intermediateStops: [],
    pricePerSeat: 180,
    pricingMode: 'flat',
    totalSeats: 4,
    availableSeats: 3,
    status: TripStatus.Published,
    allowBaggage: true,
    allowChildren: true,
    smokingAllowed: false,
    airConditioner: true,
    musicAllowed: true,
    familyFriendly: true,
    womenFriendly: true,
    comment: 'Едем аккуратно, остановки по договоренности.',
  },
  {
    id: 'trip2',
    driverId: 'demo_driver',
    vehicleId: 'veh_demo',
    fromCity: 'Душанбе',
    toCity: 'Бохтар',
    departureDate: '2026-06-03',
    departureTime: 'По наполнении',
    pickupPoint: 'Сино, рынок Саховат',
    dropoffPoint: 'Автовокзал Бохтар',
    intermediateStops: [],
    pricePerSeat: 55,
    pricingMode: 'row',
    frontSeatPrice: 70,
    secondRowPrice: 55,
    totalSeats: 4,
    availableSeats: 4,
    status: TripStatus.Published,
    allowBaggage: true,
    allowChildren: true,
    smokingAllowed: false,
    airConditioner: true,
    musicAllowed: false,
    familyFriendly: false,
    womenFriendly: false,
    comment: 'Выезд после заполнения машины.',
  },
];

export const SEED_BOOKINGS: Booking[] = [
  {
    id: 'book1',
    tripId: 'trip1',
    passengerId: 'u3',
    seatsCount: 1,
    status: BookingStatus.Pending,
    totalPrice: 180,
    passengerMessage: 'Буду у точки посадки заранее.',
    createdAt: '2026-06-02T08:00:00Z',
  },
];

export const SEED_REVIEWS: Review[] = [
  {
    id: 'rev1',
    tripId: 'trip1',
    fromUserId: 'u4',
    toUserId: 'u1',
    rating: 5,
    safetyRating: 5,
    punctualityRating: 5,
    cleanlinessRating: 4,
    politenessRating: 5,
    comment: 'Хорошая поездка, водитель вежливый.',
    createdAt: '2026-05-20T12:00:00Z',
  },
];

export const SEED_COMPLAINTS: Complaint[] = [
  {
    id: 'comp1',
    userId: 'u3',
    tripId: 'trip1',
    bookingId: 'book1',
    type: ComplaintType.PriceChanged,
    description: 'Пассажир сообщил, что цена была изменена после договоренности.',
    status: ComplaintStatus.Open,
    createdAt: '2026-06-01T12:00:00Z',
  },
];

export const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif1',
    userId: 'u1',
    title: 'Новая бронь',
    message: 'Пассажир отправил запрос на поездку Душанбе — Худжанд.',
    type: 'booking_request',
    tripId: 'trip1',
    bookingId: 'book1',
    isRead: false,
    createdAt: '2026-06-02T08:01:00Z',
  },
];
